matrix:
  include:
  - os: linux
    python: 2.7
  - os: linux
    python: 3.3
  - os: linux
    python: 3.4
  - os: linux
    python: 3.5
  - os: osx
    language: generic
    env: TOXENV=py33
  - os: osx
    language: generic
    env: TOXENV=py34
  - os: osx
    language: generic
    env: TOXENV=py35

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  # Fix for headless TravisCI
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy nose six Cython
  - python setup.py install

script:
  - cd $HOME
  - nosetests
