matrix:
  include:
  - os: linux
    python: 2.7
  - os: linux
    python: 3.3
  - os: linux
    python: 3.4
  - os: linux
    python: 3.5
  - os: osx
    language: generic
    env: TOXENV=py33
  - os: osx
    language: generic
    env: TOXENV=py34
  - os: osx
    language: generic
    env: TOXENV=py35

install:
  - pip install numpy
  - pip install six
  - pip install cython
  - python setup.py install

script:
  - cd $HOME
  - nosetests
