
environment:

  matrix:
    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"

    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"

    - PYTHON: "C:\\Python33_32"
      PYTHON_VERSION: "3.3"
      PYTHON_ARCH: "32"
      CONDA_PY: "33"

    - PYTHON: "C:\\Python33_64"
      PYTHON_VERSION: "3.3"
      PYTHON_ARCH: "64"
      CONDA_PY: "33"

    - PYTHON: "C:\\Python34_32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      CONDA_PY: "34"

    - PYTHON: "C:\\Python34_64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      CONDA_PY: "34"

    - PYTHON: "C:\\Python35_32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      CONDA_PY: "35"

    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit)
#  - powershell .\\build_tools\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Don't install from requirements-pip.txt, python-coveralls has broken dependencies on windows it seems.
#  - conda install --yes pip setuptools numpy six nose coverage Cython
  - pip install setuptools
  - pip install numpy
  - pip install six
  - pip install nose
  - pip install cython
  - python setup.py build_ext --inplace

build: false

test_script:
  # Nosetests take care of unit tests
  - nosetests

on_success:
  # Could run coveralls here but will leave that to travis tests
  - echo Build succesful!
  #- coverage report
  # coveralls
